name: Deno Test
on: [push]
jobs:
  DenoTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.37.1"
      - name: Deno Test
        run: deno test